/// dim_date is the report's date dimension. It is marked as the official date
/// table via `pbi table mark-date dim_date --date-column date` in the Desktop
/// runbook (powerbi/README.md) — that command writes the engine-validated
/// annotation. The auto-date-table internal markers (dataCategory: Time /
/// PaddedDateTableDates) are deliberately NOT hand-authored here: hand-authoring
/// them is what produced the original "not a real date table" defect.
table dim_date
	lineageTag: 27b744a9-91e0-4693-8c01-7d91cce1b303

	column date_key
		dataType: int64
		lineageTag: e7cfbfc8-26f7-4f3c-a06a-87bcd469867c
		summarizeBy: none
		sourceColumn: date_key

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 940947ed-9d31-459b-8dab-0f77c6238b7d
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		lineageTag: 54d8fa90-a4e5-4b3a-9d94-5f895253b61d
		summarizeBy: sum
		sourceColumn: year

	column quarter
		dataType: int64
		lineageTag: 6f4faffa-e0bc-4a51-853a-1994f31f3549
		summarizeBy: sum
		sourceColumn: quarter

	column month
		dataType: int64
		lineageTag: a042158e-7c2e-4844-9755-7f554ac2b98d
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		lineageTag: b11009d7-a9d2-4443-8bad-5bc488722741
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

	column week_of_year
		dataType: int64
		lineageTag: a7deb08e-c0f1-40ea-a40e-24c772cb14ac
		summarizeBy: sum
		sourceColumn: week_of_year

	column day_of_week
		dataType: string
		lineageTag: 5c29b396-e523-4b8a-8535-617f9f6eafc8
		summarizeBy: none
		sourceColumn: day_of_week

	column is_business_day
		dataType: boolean
		lineageTag: 0c463f2a-c676-417c-aa11-aa3fad501f15
		summarizeBy: none
		sourceColumn: is_business_day

	partition dim_date = m
		mode: import
		source =
				let
					Src = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Prom = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Prom, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"week_of_year", Int64.Type}, {"day_of_week", type text}, {"is_business_day", type logical}})
				in
					Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation __PBI_MarkAsDateTable = {"dt":"date"}

