table dim_rep
	lineageTag: 68b73de3-455f-40ca-bd46-1a532813131b

	column rep_key
		dataType: string
		lineageTag: abc76825-dac3-47a5-bc1b-89497ba2a84b
		summarizeBy: none
		sourceColumn: rep_key

	column rep_name
		dataType: string
		lineageTag: 5f16bca7-ac4d-4ca8-bea8-4f6855815ba1
		summarizeBy: none
		sourceColumn: rep_name

	column rep_team
		dataType: string
		lineageTag: 9c7b5993-2c3a-426c-8434-bd41876817a2
		summarizeBy: none
		sourceColumn: rep_team

	column tenure_band
		dataType: string
		lineageTag: 7997481c-f45d-4374-93c2-59cef6c18bfa
		summarizeBy: none
		sourceColumn: tenure_band

	partition dim_rep = m
		mode: import
		source =
				let
					Src = Csv.Document(File.Contents(DataFolder & "\dim_rep.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Prom = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Prom, {{"rep_key", type text}, {"rep_name", type text}, {"rep_team", type text}, {"tenure_band", type text}})
				in
					Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

