table _Measures
	lineageTag: 82560b78-8466-48ce-a380-7ed3b56fd750

	measure 'Channel · Deals' = COUNTROWS ( fact_deals )
		formatString: #,0
		lineageTag: 909c4c9b-2983-4fba-a7a9-4f1145489d91

	measure 'Channel · Won Deals' = SUM ( fact_deals[is_won] )
		formatString: #,0
		lineageTag: 2eed1882-e944-4bb8-90d9-35ecf677c121

	measure 'Channel · Lost Deals' = SUM ( fact_deals[is_lost] )
		formatString: #,0
		lineageTag: b8579b00-34fb-48bf-96de-e742af8910eb

	measure 'Channel · Win Rate' = DIVIDE ( [Channel · Won Deals], [Channel · Deals] )
		formatString: 0.0%
		lineageTag: 9cda3884-7134-4a6e-badf-fc7757d3c00b

	measure 'Channel · Volume Share' =
			DIVIDE (
			    [Channel · Deals],
			    CALCULATE ( [Channel · Deals], REMOVEFILTERS ( dim_channel ) )
			)
		formatString: 0.0%
		lineageTag: 6ce9880c-93d6-4b24-b56a-c3e220bf3de1

	/// fact_meetings_channel is an inactive relationship (the active path is
	/// fact_meetings → dim_date). USERELATIONSHIP activates the channel join so
	/// these measures attribute by channel instead of returning a grand total
	/// when sliced by dim_channel.
	measure 'Channel · Meetings Held' =
			CALCULATE (
			    COUNTROWS ( fact_meetings ),
			    fact_meetings[meeting_status] = "Held",
			    USERELATIONSHIP ( fact_meetings[channel_key], dim_channel[channel_key] )
			)
		formatString: #,0
		lineageTag: d9d1545a-16ce-4c4e-9eb8-68665749b421

	measure 'Channel · Meeting Cancel Rate' =
			DIVIDE (
			    CALCULATE (
			        COUNTROWS ( fact_meetings ),
			        fact_meetings[meeting_status] = "Cancelled",
			        USERELATIONSHIP ( fact_meetings[channel_key], dim_channel[channel_key] )
			    ),
			    CALCULATE (
			        COUNTROWS ( fact_meetings ),
			        USERELATIONSHIP ( fact_meetings[channel_key], dim_channel[channel_key] )
			    )
			)
		formatString: 0.0%
		lineageTag: 932122af-87a4-4105-a2f9-87a59cec93b1

	measure 'Revenue · Won MRR USD' = CALCULATE ( SUM ( fact_deals[mrr_usd] ), fact_deals[is_won] = 1 )
		formatString: \$#,0
		lineageTag: 0b8613c5-e271-4a5b-9161-89938d0a3de7

	measure 'Revenue · Avg MRR per Won Deal' = DIVIDE ( [Revenue · Won MRR USD], [Channel · Won Deals] )
		formatString: \$#,0
		lineageTag: bfaa82a0-1b4b-49bf-b536-b2d589bbfcd7

	measure 'Revenue · Won MRR Share' =
			DIVIDE (
			    [Revenue · Won MRR USD],
			    CALCULATE ( [Revenue · Won MRR USD], REMOVEFILTERS ( dim_channel ) )
			)
		formatString: 0.0%
		lineageTag: 8957b27e-ced9-4bc7-97d2-bdadd0610004

	measure 'Channel · Dialer Hours' = SUM ( fact_deals[dialer_hours_attributed] )
		formatString: #,0.0
		lineageTag: 6b010410-f42a-42a8-9a79-af776a2e0a97

	/// THE HEADLINE METRIC. Won MRR returned per hour of sales-dialer capacity
	/// consumed. Only dialer-motion channels (Cold Calling, Re-bookings) have
	/// non-zero dialer hours, so this is blank for every other channel by design
	/// — that blank is the point: warm channels return revenue at zero dialer cost.
	measure 'Channel · MRR per Dialer Hour' = DIVIDE ( [Revenue · Won MRR USD], [Channel · Dialer Hours] )
		formatString: \$#,0
		lineageTag: feb5d121-4c77-4b2a-b6ce-22c3fcecdb36

	measure 'Channel · Avg Days to Won' =
			CALCULATE (
			    AVERAGE ( fact_deals[deal_age_days] ),
			    fact_deals[is_won] = 1
			)
		formatString: 0.0
		lineageTag: e591fc5c-49c1-44e8-9008-ecbd34b9d600

	measure 'Channel · Cancellation Share of Losses' =
			DIVIDE (
			    CALCULATE ( [Channel · Lost Deals], dim_lost_reason[lost_reason] = "Meeting No-Show / Cancelled" ),
			    [Channel · Lost Deals]
			)
		formatString: 0.0%
		lineageTag: 23638bed-72c8-4028-a084-fb40b95a976a

	/// Re-booking trap flag: 1 when the selected channel is Re-bookings — a
	/// channel by org-chart, a churn motion by economics (lowest win rate,
	/// highest cancel rate, heavy dialer burn, negligible MRR returned).
	measure 'Channel · Re-booking Trap Flag' = IF ( SELECTEDVALUE ( dim_channel[channel_name] ) = "Re-bookings", 1, 0 )
		formatString: 0
		lineageTag: 420d97ce-73ac-4784-a281-20499673087b

	// ----------------------------------------------------------------------
	// Phase 8 — post-won churn / retention (the post-sale axis).
	// is_churned / churned_mrr live on fact_deals itself, so every measure
	// below sums over the ACTIVE fact_deals to dim_channel relationship with
	// a plain CALCULATE filter. No RELATED, no inactive-relationship
	// traversal (that class of bug is uncatchable by pbi validate and the
	// offline MCP; the safe construction is encoded here by design).
	//
	// WARNING: Power BI Desktop strips these on save (it writes back only the
	// loaded model). If the count drops below 20, re-assert this block before
	// rebuilding the report. _gen_report.py guards on the count.
	// ----------------------------------------------------------------------

	/// Won customers that cancelled within the 12-month observation window.
	measure 'Channel · Churned Deals' = CALCULATE ( SUM ( fact_deals[is_churned] ), fact_deals[is_won] = 1 )
		formatString: #,0
		lineageTag: 5a1c7e60-0c2b-4d11-9f3a-1b6e44d90a01

	/// Share of WON customers still active at month 12 (logo retention).
	/// Small-n channels (Re-bookings ~14 won, Instagram, SEO) are directional.
	measure 'Channel · Retention Rate' =
			VAR Won = [Channel · Won Deals]
			RETURN
			    IF ( Won > 0, 1 - DIVIDE ( [Channel · Churned Deals], Won ) )
		formatString: 0.0%
		lineageTag: 5a1c7e60-0c2b-4d11-9f3a-1b6e44d90a02

	/// Won MRR that churned within the window.
	measure 'Revenue · Churned MRR' = CALCULATE ( SUM ( fact_deals[churned_mrr] ), fact_deals[is_won] = 1 )
		formatString: \$#,0
		lineageTag: 5a1c7e60-0c2b-4d11-9f3a-1b6e44d90a03

	/// Net revenue retention (gross of expansion, no upsell modelled):
	/// won MRR that did NOT churn, over won MRR.
	measure 'Revenue · Net Revenue Retention' =
			DIVIDE (
			    [Revenue · Won MRR USD] - [Revenue · Churned MRR],
			    [Revenue · Won MRR USD]
			)
		formatString: 0.0%
		lineageTag: 5a1c7e60-0c2b-4d11-9f3a-1b6e44d90a04

	/// Won customers retained through the window.
	measure 'Channel · Won & Retained' = [Channel · Won Deals] - [Channel · Churned Deals]
		formatString: #,0
		lineageTag: 5a1c7e60-0c2b-4d11-9f3a-1b6e44d90a05

	column _
		dataType: string
		lineageTag: cc8804ef-9b69-422a-9989-cf2cbb777b29
		summarizeBy: none
		sourceColumn: _

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
					Source = Table.FromRows({}, {"_"})
				in
					Source

	annotation PBI_ResultType = Table

